Apathy Fixes & Minor Revamp
quotefox/Hyper-Station-13 pull request #1237
Opened 2021-06-06 22:29 UTC by ArchieBeepBoop

## About The Pull Request

Killing anything that was a carbon in the game (including monkeys, xenos, and anything else that was a carbon was causing 20 minutes of the seeing someone die negative moodlet. This is especially bad for people that work in xenobio/medical.

This makes it so apathy will prevent one from getting that negative moodlet and also nerfs that moodlet's negative values and overall impact in the game.

## Why It's Good For The Game

20 minutes was way too much, -8 is way too much especially in scenarios where people are dying left and right and medical needs to act quickly.

## Changelog
:cl:
fix: Seeing anything that's not a human die will no longer trigger a mood debuff
add: Apathy now prevents you from getting the deathsaw negative moodlet
tweak: Seeing someone die no longer kills your movement for 20 minutes. This was especially harmful for medical personnel in busy rounds.
/:cl:

2021-06-07 17:07 UTC, Dahlular requested changes
I think the values and times are completely okay, as we're a server that doesn't deal with death left and right too often. Death is still death and we're a roleplay server-- however, the change that it should only affect humans is a very good change.

2021-06-07 19:17 UTC, ArchieBeepBoop commented
> I think the values and times are completely okay, as we're a server that doesn't deal with death left and right too often. Death is still death and we're a roleplay server-- however, the change that it should only affect humans is a very good change.
I still think these values are waaaaaay too overtuned and have done nothing but hamper medical. The human only change is good but we should at least halve the death punishment.

2021-06-12 00:39 UTC, Dahlular requested changes

2021-06-12 00:39 UTC, Dahlular commented on hyperstation/code/datums/mood_events/events.dm
> +	timeout = 10 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
```suggestion
	timeout = 20 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
```
If we're nerfing the mood change and allowing medical doctors to be resistant to it, I ask that we keep the excessive time of 20 minutes. It is someone dying, after all.

2021-06-12 00:42 UTC, ArchieBeepBoop commented on hyperstation/code/datums/mood_events/events.dm
> +	timeout = 10 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
I guess we could leave it 20, but I'd honestly prefer it to be something lower, since it will also affect security and others even in an emergency situation. Or if we're keeping it to 20, we could reduce the moodlet to -3 instead so it isn't as big of a hit.

2021-06-12 00:43 UTC, ArchieBeepBoop commented on hyperstation/code/datums/mood_events/events.dm
> +	timeout = 10 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
This was also slightly recently discussed in dev talk, people were hoping for either a middle ground of 10-15 minutes with a medium debuff or a lower reduction that lasts the full time.

2021-06-12 00:45 UTC, Dahlular commented on hyperstation/code/datums/mood_events/events.dm
> +	timeout = 10 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
It affects everyone on the station; including antagonists (which admittedly is to a lesser degree since they have that funny big mood boost); making killing more punishing. With the fact that it doesn't affect medical, that makes medical's lives easier to be the ones dealing with death, since it is their job after all.
I'd like to playtest these values for a little bit live, and if they're still too much, we can tone them down.

2021-06-12 00:54 UTC, ArchieBeepBoop commented on hyperstation/code/datums/mood_events/events.dm
> +	timeout = 10 MINUTES //20 minutes is too much, medical is moving around sluggishly because of this constantly.
Fair enough.

2021-06-12 00:57 UTC, Dahlular approved these changes

2021-06-12 00:57 UTC, merged