Carp Team Random Event
quotefox/Hyper-Station-13 pull request #466
Opened 2020-09-16 19:43 UTC by ArchieBeepBoop

## About The Pull Request

A ghost role random event spawn with a weight of 5. This allows up to 3 ghost players to spawn as a team of sentient carps around the station.
There's a 1% chance that they will spawn as a magicarp (red carp), 15% chance they will spawn as a shark carp and if neither, a regular carp. Regardless of carp type, they have a maximum of 120 HP. This can be fine tuned if needed.~

## Why It's Good For The Game

Adds a little bit of variety. Also, carps are fun.
![image](https://user-images.githubusercontent.com/53913550/93384651-82d55780-f83b-11ea-8468-65a27f36d9c9.png)

## Changelog
:cl:
add: Carp Team ghost role spawn
/:cl:

2020-09-16 22:14 UTC, ArchieBeepBoop commented
Changed to reflect @Dahlular 's requests. 18 should be a good amount of players to stop 3 carps if they are doing antag stuff.

2020-09-19 15:13 UTC, Dahlular requested changes
Thinking it over, I'll be honest, as much as I want this, I know just how much damage one sentient carp can do (Thanks Citadel), so I'd prefer this have a weight of 0 to remain adminbus only.

2020-09-19 16:08 UTC, Dahlular approved these changes

2020-09-19 16:09 UTC, ArchieBeepBoop commented
Done!

2020-09-19 16:09 UTC, merged