Space Carp Updates
quotefox/Hyper-Station-13 pull request #551
Opened 2020-10-04 08:52 UTC by ArchieBeepBoop

## About The Pull Request

Makes it so shark carps aren't that shitty by porting updates directly from citadel. Also slightly buffs regular carp HP.

## Why It's Good For The Game

Balance, updates. Regular carps are still not allowed to regen, if that's the question. Only mega. Cayenne also gets a fix which tags it as a carp, so that other carps won't attack it.

## Changelog
:cl:
tweak: carpy bois
/:cl:

2020-10-04 09:23 UTC, Dahlular requested changes
I like this, but just leave carp at the normal amount of health; the space shark changes are fine. I know you love your carp teams, but I don't want them to become god.

2020-10-04 13:12 UTC, ArchieBeepBoop commented
> I like this, but just leave carp at the normal amount of health; the space shark changes are fine. I know you love your carp teams, but I don't want them to become god.

Oh, uh. Carp team have set health values. This should not affect it.

2020-10-05 03:19 UTC, Dahlular commented
Okay but regardless, carp don't need a buff in their health.

2020-10-05 03:50 UTC, ArchieBeepBoop commented
A'ight, health buff removed.

2020-10-06 03:45 UTC, Dahlular approved these changes

2020-10-06 03:45 UTC, merged