Ports Lia / Micro Carp Buff?
quotefox/Hyper-Station-13 pull request #607
Opened 2020-10-20 05:52 UTC by ArchieBeepBoop

## About The Pull Request

Ports Lia, the head of security space carp directly from https://github.com/tgstation/tgstation/pull/52717 and allowing mappers to place her.

Also partially ports the carp buff from https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10894

![image](https://64.media.tumblr.com/717a0571765be222d7ac6da5b9e97a9b/tumblr_p5rht55HXS1uhh267o6_540.gifv)

## Why It's Good For The Game

Carp hp buffs: They go down in 2-3 hits with a spear/tool box and are still not that much of a threat to anyone in space, especially your usual engineer or miner holding the default, out of the box 40 damage PKA. This is more of a change to try and remedy the fact that any space carp that attacks a door has the chance of being one shot by the door's zap mechanics.

## Changelog
:cl:
add: Carps have evolved to take more damage
tweak: Kinaris' pet budget has increased, and the HoS's missing pet has been found.
/:cl:

2020-10-20 06:57 UTC, Bran34 commented
lia is my spirit animal

2020-10-23 22:10 UTC, Dahlular requested changes
The energy harvester is gonna need a discussion; however, you really need to stop trying to buff carps.

2020-10-23 22:19 UTC, ArchieBeepBoop commented
> The energy harvester is gonna need a discussion; however, you really need to stop trying to buff carps.

Carp buff removed.

As for the harvester, default SM setup excess power should give you about 90 credits each minute. You -have- to go overboard with power generation if you want to make a good sum of credits from it.

2020-10-23 22:25 UTC, Dahlular approved these changes

2020-10-23 22:25 UTC, merged