Kinaris Corp 1.1.2
quotefox/Hyper-Station-13 pull request #707
Opened 2020-11-21 17:10 UTC by Oposshim

another long overdue haul of shit I forgot/was to busy to get the first patch around.

## About The Pull Request
a part two to the first overhaul PR I'm doing

## Why It's Good For The Game
N/A, Lore, Tryin' to make Dahl happy ree

## Changelog
:cl:
Added new safe kin cig pack / removed the nazi vendor / edited base terms of nanotrasen to kinaris / secondary mentions of nanotrasen on station are desc to sound stolen tech / finally dealt with the pesky potted plants and retina burning custom UI
/:cl:

2020-11-21 18:01 UTC, ArchieBeepBoop commented
Note: I wouldn't add omni to base cigs. Unless they're a premium which can be acquired with coins.

2020-11-21 18:02 UTC, ArchieBeepBoop commented
Also, why are we making all comms agents donk co agents?

2020-11-21 22:20 UTC, TotallyNotADog commented
> Also, why are we making all comms agents donk co agents?

because poss has some sort of obsession with donk co and seems to be trying to force it on everyone else.

additionally: this pr overwrites sprites instead of adding new ones, just like the NT -> KN sign changes you made before. Nanotrasen _still exists_ as a company in the lore, so add new KN themed stuff instead of outright replacing them.

2020-11-21 22:35 UTC, TotallyNotADog reviewed
Looking over it, this has a bunch more stuff to fix, Poss.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/cargo/packs/armory.dm
> +	desc = "Contains two fullbody sets of tough, fireproof, pressurized suits designed in a joint effort by Earth-Gov and Kinaris. Each set contains a suit, helmet, mask, combat belt, and combat gloves.
changing companies =/= rewriting history. the swat suit was still designed by NT and this IS-ERI company

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A tactical relic of years past before Valorie decided it was cheaper to dye the suits red instead of washing out the blood."
should be Valarie, not Valorie. Also, why not just have it say Kinaris?

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A formal relic of years past before Valorie decided it was cheaper to dye the suits red instead of washing out the blood."
same as the previous instance of Valorie

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/ruins/lavaland_ruin_code.dm
> +	flavour_text = "<span class='big bold'>You are a Donk.Corp branch syndicate agent,</span><b> employed in a top secret research facility developing biological weapons plants and toys. Unfortunately,
no reason to specify which company it's actually part of. Leave it as generic syndicate.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/ruins/lavaland_ruin_code.dm
> +	flavour_text = "<span class='big bold'>You are a Donk.Corp branch syndicate agent,</span><b> employed in a top secret research facility developing biological weapons plants and toys. Unfortunately,
I don't see a reason to change it from Comms to Intel other than to spur confusion. And again, no need to specify it to be Donk co

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/station_goals/bsa.dm
> +	 -Val's personal Naval Command"}
Kinaris isn't only made up of Valarie, it's a mega organization like NT is. Just say "Kinaris Naval Command"

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/ruins/lavaland_ruin_code.dm
> +	name = "Lavaland Syndicate Intel Agent"
Again, no reason to change it from Comms to Intel.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A tactical security jumpsuit for officers complete with Kinaris PMC belt buckle."
Unsure if you should include the Private Military Contractor (PMC) part but it's not major so eh

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/cargo/packs/armory.dm
> +	desc = "Contains three sharpened combat knives. Each knife guaranteed to fit snugly inside any of those stolen Nanotrasen-standard boot. Requires Armory access to open."
Grammatical error. Keep it as Nanotrasen-standard since it being stolen doesn't change what it actually is.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/game/objects/items/devices/PDA/radio.dm
> +	desc = "An electronic radio system of stolen Nanotrasen design."
No reason to change this

2020-11-21 22:35 UTC, TotallyNotADog commented on code/game/machinery/camera/camera_assembly.dm
> +	desc = "The basic construction kit for a cam-corder setup."
They're security cameras, not camcorders. for reference, a camcorder looks like this:
![image](https://user-images.githubusercontent.com/66381600/99889023-0c781b80-2c17-11eb-9d69-7002eb751265.png)

Also, it's not a kit for constructing a camera, it's the literal construction _of_ the camera, i.e. the frame.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/game/machinery/camera/camera_assembly.dm
> +	desc = "The basic construction kit for a cam-corder setup."
Same as above.

2020-11-21 22:35 UTC, TotallyNotADog commented on code/modules/vending/cigarette.dm
> +					/obj/item/storage/fancy/cigarettes/smokekins = 5,
These have omnizine in them. As Archie said, move them to premium.

2020-11-21 23:50 UTC, VladinXXV commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A tactical relic of years past before Valorie decided it was cheaper to dye the suits red instead of washing out the blood."
Should just stay as NT. They decided it was cheaper to dye the suits red, this is another rewriting history thing.

2020-11-21 23:55 UTC, VladinXXV requested changes

2020-11-21 23:55 UTC, VladinXXV commented on code/modules/ruins/lavaland_ruin_code.dm
> +	flavour_text = "<span class='big bold'>You are a Donk.Corp branch syndicate agent,</span><b> employed in a top secret research facility developing biological weapons plants and toys. Unfortunately,
Why are we removing, "Use the communication equipment to provide support to any field agents"? That's the entire fucking point of a comms agent. You work with the traitors.

2020-11-22 02:59 UTC, VladinXXV approved these changes
Good shit.
*to be clear I'm just approving the changes to the cigs

2020-11-22 03:03 UTC, VladinXXV requested changes
Why exactly are we deleting the entire armory crate selection from cargo?

2020-11-22 03:16 UTC, VladinXXV commented on code/game/machinery/camera/camera_assembly.dm
> +	desc = "The basic construction for Nanotrasen-Always-Watching-You cameras.
missing a closing quotation mark

2020-11-22 03:16 UTC, VladinXXV commented on code/game/machinery/camera/camera_assembly.dm
> +	desc = "The basic construction for Nanotrasen-Always-Watching-You cameras.
same here

2020-11-22 03:17 UTC, VladinXXV requested changes
bro closing quotes please

2020-11-22 03:23 UTC, TotallyNotADog commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A tactical relic of years past before it decided it was cheaper to dye the suits red instead of washing out the blood."
Using "it" here makes it seem like the jumpsuit somehow decided to dye itself red. Change to Kinaris or "it was"

2020-11-27 14:40 UTC, merged